#include "vb/text_match.h"
#include <algorithm>
#include <set>
#include <unordered_map>
namespace vb {
bool decode_utf8(const std::string& s,std::vector<uint32_t>& o){o.clear(); for(size_t i=0;i<s.size();){uint8_t c=s[i++];uint32_t x=0;int n=0;if(c<0x80)x=c;else if((c&0xe0)==0xc0){x=c&31;n=1;}else if((c&0xf0)==0xe0){x=c&15;n=2;}else if((c&0xf8)==0xf0){x=c&7;n=3;}else return false;if(i+n>s.size())return false;for(int k=0;k<n;k++){uint8_t q=s[i++];if((q&0xc0)!=0x80)return false;x=(x<<6)|(q&63);}if((n==1&&x<0x80)||(n==2&&x<0x800)||(n==3&&x<0x10000)||x>0x10ffff||(x>=0xd800&&x<=0xdfff))return false;o.push_back(x);}return true;}
bool parse_text_patterns(const Json& j,std::vector<TextPattern>& out,std::string& e){out.clear();if(!j.is_array()||j.size()>16){e="accept must contain 0..16 patterns";return false;}for(auto&p:j){if(!p.is_array()||p.empty()||p.size()>8){e="accept pattern must contain 1..8 segments";return false;}TextPattern q;for(auto&s:p){if(!s.is_object()||!s.contains("set")||!s.at("set").is_string()){e="accept segment set must be UTF-8 string";return false;}TextPatternSegment z; if(!decode_utf8(s.at("set").get<std::string>(),z.set)||z.set.empty()){e="accept segment set invalid UTF-8";return false;}auto mi=s.find("min"),ma=s.find("max");if(mi!=s.end()&&!mi->is_number_integer()){e="accept segment min must be integer";return false;}if(ma!=s.end()&&!ma->is_number_integer()){e="accept segment max must be integer";return false;}auto bounded=[&](const Json::const_iterator& it,int def,int& dst){if(it==s.end()){dst=def;return true;}if(it->is_number_unsigned()){auto v=it->get<uint64_t>();if(v>16)return false;dst=static_cast<int>(v);return true;}auto v=it->get<int64_t>();if(v<0||v>16)return false;dst=static_cast<int>(v);return true;};if(!bounded(mi,0,z.min)||!bounded(ma,z.min,z.max)||z.max<z.min){e="accept segment min/max out of range";return false;}q.push_back(std::move(z));}out.push_back(std::move(q));}return true;}
static bool rec(const TextPattern&p,const std::vector<uint32_t>&c,size_t i,size_t pos,std::unordered_map<uint64_t,bool>& memo){if(i==p.size())return pos==c.size();const uint64_t key=(static_cast<uint64_t>(i)<<32)|static_cast<uint64_t>(pos);auto it=memo.find(key);if(it!=memo.end())return it->second;for(int n=p[i].min;n<=p[i].max&&pos+static_cast<size_t>(n)<=c.size();++n){bool ok=true;for(int k=0;k<n;k++)if(std::find(p[i].set.begin(),p[i].set.end(),c[pos+k])==p[i].set.end()){ok=false;break;}if(ok&&rec(p,c,i+1,pos+static_cast<size_t>(n),memo))return memo[key]=true;}return memo[key]=false;}
bool text_matches(const std::string&t,const std::vector<TextPattern>&p){std::vector<uint32_t>c;if(!decode_utf8(t,c))return false;if(p.empty())return true;for(auto&q:p){size_t total_min=0,total_max=0;for(const auto&s:q){total_min+=static_cast<size_t>(s.min);total_max+=static_cast<size_t>(s.max);}if(c.size()<total_min||c.size()>total_max)continue;std::unordered_map<uint64_t,bool> memo;if(rec(q,c,0,0,memo))return true;}return false;}
}
