#include <algorithm>
#include <cmath>
#include <cstdio>
#include <limits>
#include <memory>
#include <mutex>
#include <unordered_map>
#include <vector>
#include <onnxruntime_c_api.h>
#include "cpu_backend.h"
#include "sha256.h"
#include "vb/decoder.h"

namespace vb { namespace {
const OrtApi* ort(){static const OrtApi*p=OrtGetApiBase()->GetApi(ORT_API_VERSION);return p;}
bool ck(OrtStatus*s,const char*w,std::string&e){if(!s)return true;const char*m=ort()->GetErrorMessage(s);e=std::string("stage2 ort: ")+w+": "+(m?m:"?");ort()->ReleaseStatus(s);return false;}
bool load(const std::string&p,std::vector<uint8_t>&b,std::string&e){FILE*f=std::fopen(p.c_str(),"rb");if(!f){e="cannot open stage2 model: "+p;return false;}if(std::fseek(f,0,SEEK_END)!=0){std::fclose(f);e="cannot seek stage2 model";return false;}long n=std::ftell(f);if(n<=0||static_cast<size_t>(n)>kCpuMaxModelBytes){std::fclose(f);e="stage2 model is empty or too large";return false;}std::rewind(f);b.resize(static_cast<size_t>(n));bool q=std::fread(b.data(),1,b.size(),f)==b.size();std::fclose(f);if(!q)e="cannot read stage2 model";return q;}
struct Session{std::vector<uint8_t>b;OrtSession*s=nullptr;std::string in,out;int it=-1,ot=-1;std::vector<int64_t> id,od;~Session(){if(s)ort()->ReleaseSession(s);}};
std::mutex cache_mu; std::mutex create_mu;std::unordered_map<std::string,std::weak_ptr<Session>> cache;
bool product(const std::vector<int64_t>&d,size_t&n){n=1;for(auto x:d){if(x<=0||static_cast<uint64_t>(x)>std::numeric_limits<size_t>::max()/n)return false;n*=static_cast<size_t>(x);}return true;}
std::shared_ptr<Session> session_for(const Stage2Spec&x,std::string&e){std::vector<uint8_t>b;if(!load(x.model_path,b,e))return{};std::string k=sha256_hex(b)+":"+std::to_string(x.in_h)+"x"+std::to_string(x.in_w)+":"+(x.bgr?"bgr":"rgb")+":"+std::to_string(x.scale);for(float v:x.mean)k+=":"+std::to_string(v);{std::lock_guard<std::mutex>l(cache_mu);auto i=cache.find(k);if(i!=cache.end())if(auto p=i->second.lock())return p;}std::lock_guard<std::mutex> create_lk(create_mu);{std::lock_guard<std::mutex>l(cache_mu);auto i=cache.find(k);if(i!=cache.end())if(auto p=i->second.lock())return p;}auto p=std::make_shared<Session>();p->b=std::move(b);OrtSessionOptions*o=nullptr;if(!ck(ort()->CreateSessionOptions(&o),"options",e))return{};OrtEnv*en=cpu_ort_env(e);bool q=en&&ck(ort()->CreateSessionFromArray(en,p->b.data(),p->b.size(),o,&p->s),"session",e);ort()->ReleaseSessionOptions(o);if(!q)return{};OrtAllocator*a=nullptr;size_t ni=0,no=0;char*in=nullptr,*out=nullptr;q=ck(ort()->GetAllocatorWithDefaultOptions(&a),"allocator",e)&&ck(ort()->SessionGetInputCount(p->s,&ni),"input count",e)&&ck(ort()->SessionGetOutputCount(p->s,&no),"output count",e);if(q&&(ni!=1||no!=1)){e="stage2 expects one input and one output";q=false;}if(q)q=ck(ort()->SessionGetInputName(p->s,0,a,&in),"input name",e)&&ck(ort()->SessionGetOutputName(p->s,0,a,&out),"output name",e);if(in){p->in=in;a->Free(a,in);}if(out){p->out=out;a->Free(a,out);}OrtTypeInfo*t=nullptr;const OrtTensorTypeAndShapeInfo*ti=nullptr;size_t nd=0;if(q)q=ck(ort()->SessionGetInputTypeInfo(p->s,0,&t),"input type",e)&&ck(ort()->CastTypeInfoToTensorInfo(t,&ti),"input tensor",e)&&ck(ort()->GetDimensionsCount(ti,&nd),"input rank",e);if(q){p->id.resize(nd);q=ck(ort()->GetDimensions(ti,p->id.data(),nd),"input shape",e);if(q){ONNXTensorElementDataType z=ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED; if(!ck(ort()->GetTensorElementType(ti,&z),"input dtype",e)) q=false; p->it=z;};}if(t)ort()->ReleaseTypeInfo(t);t=nullptr;ti=nullptr;if(q)q=ck(ort()->SessionGetOutputTypeInfo(p->s,0,&t),"output type",e)&&ck(ort()->CastTypeInfoToTensorInfo(t,&ti),"output tensor",e)&&ck(ort()->GetDimensionsCount(ti,&nd),"output rank",e);if(q){p->od.resize(nd);q=ck(ort()->GetDimensions(ti,p->od.data(),nd),"output shape",e);if(q){ONNXTensorElementDataType z=ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED; if(!ck(ort()->GetTensorElementType(ti,&z),"output dtype",e)) q=false; p->ot=z;};}if(t)ort()->ReleaseTypeInfo(t);if(!q)return{};if(p->it!=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT||p->id.size()!=4||p->id[0]!=1||p->id[1]!=3||p->id[2]!=x.in_h||p->id[3]!=x.in_w){e="stage2 input must be static float32 NCHW [1,3,H,W] matching input_hw";return{};}if(p->ot!=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT||((p->od.size()!=2 && (p->od.size()!=3 && p->od.size()!=4 || p->od[0]!=1 || (p->od.size()==4 && p->od[2]!=1))))){e="stage2 output must be float32 [C,T] or [1,C,T]";return{};}size_t n=0;if(!product(p->od,n)||!n){e="stage2 output shape is invalid";return{};}cache[k]=p;return p;}
class CpuStage2 final:public Stage2Context{public:explicit CpuStage2(const Stage2Spec&x,std::string&e):sp_(x),s_(session_for(x,e)),ready_(!!s_){}int infer_crops(const FrameBuf&f,const CropReq*c,size_t n,TensorView*o,std::string&e)override{if(!ready_){e="stage2 session is not ready";return-1;}if(!c||!o||f.mem!=Mem::Host||!f.host||(f.fmt!=PixFmt::RGB888&&f.fmt!=PixFmt::BGR888)){e="stage2 cpu needs a valid host RGB888/BGR888 frame";return-1;}if(f.w<=0||f.h<=0||f.stride<f.w*3){e="stage2 frame dimensions/stride invalid";return-1;}stores_.clear();stores_.reserve(n);for(size_t i=0;i<n;++i){if(!valid(c[i])){e="stage2 crop bbox is invalid";return-1;}prep(f,c[i]);if(!run(o[i],e))return-1;}return 0;}int infer_rgb(const uint8_t*p,int w,int h,int stride,TensorView*o,std::string&e)override{if(!p||w<=0||h<=0||stride<w*3){e="stage2 infer_rgb frame invalid";return-1;}FrameBuf f;f.w=w;f.h=h;f.stride=stride;f.host=p;f.mem=Mem::Host;f.fmt=PixFmt::RGB888;CropReq c{0,0,1,1};return infer_crops(f,&c,1,o,e);}private:static bool valid(const CropReq&c){return std::isfinite(c.x0)&&std::isfinite(c.y0)&&std::isfinite(c.x1)&&std::isfinite(c.y1)&&c.x0>=0&&c.y0>=0&&c.x1<=1&&c.y1<=1&&c.x0<c.x1&&c.y0<c.y1;}
void prep(const FrameBuf&f,const CropReq&c){size_t pl=static_cast<size_t>(sp_.in_w)*sp_.in_h;in_.assign(pl*3,0);float x0,y0,x1,y1,ox=0,oy=0;int bw,bh;if(f.letterboxed){f.geom.to_model_norm(c.x0,c.y0,x0,y0);f.geom.to_model_norm(c.x1,c.y1,x1,y1);bw=f.w;bh=f.h;}else{int fw=f.full_w>0?f.full_w:f.w,fh=f.full_h>0?f.full_h:f.h;x0=c.x0;y0=c.y0;x1=c.x1;y1=c.y1;bw=fw;bh=fh;ox=f.crop_x0;oy=f.crop_y0;}x0=x0*bw-ox;x1=x1*bw-ox;y0=y0*bh-oy;y1=y1*bh-oy;for(int y=0;y<sp_.in_h;++y)for(int x=0;x<sp_.in_w;++x){float sx=x0+(x+.5f)*(x1-x0)/sp_.in_w-.5f,sy=y0+(y+.5f)*(y1-y0)/sp_.in_h-.5f;sx=std::clamp(sx,0.0f,static_cast<float>(f.w-1));sy=std::clamp(sy,0.0f,static_cast<float>(f.h-1));int ax=static_cast<int>(std::floor(sx)),ay=static_cast<int>(std::floor(sy)),bx=std::min(ax+1,f.w-1),by=std::min(ay+1,f.h-1);float fx=sx-ax,fy=sy-ay;const uint8_t*p00=f.host+static_cast<size_t>(ay)*f.stride+ax*3,*p01=f.host+static_cast<size_t>(ay)*f.stride+bx*3,*p10=f.host+static_cast<size_t>(by)*f.stride+ax*3,*p11=f.host+static_cast<size_t>(by)*f.stride+bx*3;for(int k=0;k<3;++k){float v=(p00[k]*(1-fx)+p01[k]*fx)*(1-fy)+(p10[k]*(1-fx)+p11[k]*fx)*fy;int ch=(f.fmt==PixFmt::BGR888)?2-k:k;if(sp_.bgr)ch=2-ch;in_[static_cast<size_t>(ch)*pl+static_cast<size_t>(y)*sp_.in_w+x]=v*sp_.scale-sp_.mean[ch];}}}
bool run(TensorView&o,std::string&e){int64_t d[4]={1,3,sp_.in_h,sp_.in_w};OrtMemoryInfo*mi=nullptr;OrtValue*iv=nullptr;if(!ck(ort()->CreateCpuMemoryInfo(OrtArenaAllocator,OrtMemTypeDefault,&mi),"memory",e))return false;bool q=ck(ort()->CreateTensorWithDataAsOrtValue(mi,in_.data(),in_.size()*sizeof(float),d,4,ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,&iv),"input",e);ort()->ReleaseMemoryInfo(mi);if(!q)return false;const char*ni[1]={s_->in.c_str()},*no[1]={s_->out.c_str()};OrtValue*ov=nullptr;q=ck(ort()->Run(s_->s,nullptr,ni,&iv,1,no,1,&ov),"Run",e);ort()->ReleaseValue(iv);if(!q||!ov)return false;OrtTypeInfo*t=nullptr;const OrtTensorTypeAndShapeInfo*ti=nullptr;size_t nd=0;q=ck(ort()->GetTypeInfo(ov,&t),"type",e)&&ck(ort()->CastTypeInfoToTensorInfo(t,&ti),"tensor",e)&&ck(ort()->GetDimensionsCount(ti,&nd),"rank",e);std::vector<int64_t>sh(nd);if(q)q=ck(ort()->GetDimensions(ti,sh.data(),nd),"shape",e);bool shape_ok=(sh.size()==2|(sh.size()==3 && sh[0]==1)|(sh.size()==4 && sh[0]==1 && sh[2]==1)); if(!shape_ok) q=false; ONNXTensorElementDataType typ=ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED; if(q && !ck(ort()->GetTensorElementType(ti,&typ),"output dtype",e)) q=false;size_t n=0;if(q)q=product(sh,n)&&typ==ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT;if(!q){e="stage2 output dtype/element count invalid";if(t)ort()->ReleaseTypeInfo(t);ort()->ReleaseValue(ov);return false;}float*data=nullptr;q=ck(ort()->GetTensorMutableData(ov,reinterpret_cast<void**>(&data)),"data",e);if(q){if(sh.size()==3)sh.erase(sh.begin()); else if(sh.size()==4 && sh[0]==1 && sh[2]==1){sh.erase(sh.begin());sh.erase(sh.begin()+1);}stores_.emplace_back(data,data+n);o.data=stores_.back().data();o.count=n;o.dims=std::move(sh);o.dtype=0;o.raw_data=nullptr;}if(t)ort()->ReleaseTypeInfo(t);ort()->ReleaseValue(ov);return q;}
Stage2Spec sp_;std::shared_ptr<Session>s_;std::vector<float>in_;std::vector<std::vector<float>>stores_;bool ready_=false;};}
std::unique_ptr<Stage2Context>make_cpu_stage2(const Stage2Spec&s,std::string&e){e.clear();auto p=std::make_unique<CpuStage2>(s,e);return e.empty()?std::move(p):nullptr;}
}
