// Jetson NVDEC source adapted from fall-detection@5af128d (Apache-2.0).
// Modified for BGRx->compact BGR888 FrameBuf; no OpenCV and no zero-copy claim.
#include "trt_source.h"
#include "vb/json.h"
#include <gst/gst.h>
#include <gst/app/gstappsink.h>
#include <gst/rtsp/gstrtsptransport.h>
#include <gst/video/video.h>
#include <chrono>
#include <cctype>
#include <cstring>
#include <mutex>
namespace vb { namespace {
double mono(){using namespace std::chrono;return duration_cast<duration<double>>(steady_clock::now().time_since_epoch()).count();}
double wall(){using namespace std::chrono;return duration<double,std::milli>(system_clock::now().time_since_epoch()).count();}
struct PadCtx{GstElement* next=nullptr;const char* enc="H264";};
void pad_added(GstElement*,GstPad*p,gpointer u){auto*c=static_cast<PadCtx*>(u);GstCaps*x=gst_pad_get_current_caps(p);if(!x)x=gst_pad_query_caps(p,nullptr);bool yes=false;if(x&&gst_caps_get_size(x)){auto*s=gst_caps_get_structure(x,0);const char*m=gst_structure_get_string(s,"media");const char*e=gst_structure_get_string(s,"encoding-name");yes=m&&e&&!std::strcmp(m,"video")&&!std::strcmp(e,c->enc);}if(x)gst_caps_unref(x);if(yes){GstPad*q=gst_element_get_static_pad(c->next,"sink");if(q&&!gst_pad_is_linked(q))gst_pad_link(p,q);if(q)gst_object_unref(q);}}
class NvSource final:public FrameSource{
public:
 explicit NvSource(StreamSpec s):spec_(std::move(s)){} ~NvSource()override{close();}
 bool prepare(std::string&e){std::lock_guard<std::mutex>l(mu_);return pipeline_||build(e);}
 bool open(std::string&e)override{std::lock_guard<std::mutex>l(mu_);e.clear();if(playing_)return true;if(!pipeline_&&!build(e))return false;if(!started_requested_){auto r=gst_element_set_state(pipeline_,GST_STATE_PLAYING);if(r==GST_STATE_CHANGE_FAILURE){e=bus_error_locked("NVDEC pipeline failed to start");if(e.empty())e="NVDEC pipeline failed to start";close_locked();return false;}started_requested_=true;}GstState st=GST_STATE_NULL,pending=GST_STATE_VOID_PENDING;auto r=gst_element_get_state(pipeline_,&st,&pending,0);std::string state_error=bus_error_locked("");if(!state_error.empty()){e=state_error;close_locked();return false;}if(r==GST_STATE_CHANGE_FAILURE){e="NVDEC pipeline failed to reach PLAYING";close_locked();return false;}if(r==GST_STATE_CHANGE_ASYNC||pending!=GST_STATE_VOID_PENDING){e="NVDEC pipeline state pending: current=";e+=gst_element_state_get_name(st);e+=" pending=";e+=gst_element_state_get_name(pending);return false;}if(st!=GST_STATE_PLAYING)return false;playing_=true;seq_=0;failed_.clear();return true;}
 int read(FrameBuf&o,int timeout)override{GstElement*sink=nullptr;{std::lock_guard<std::mutex>l(mu_);if(!pipeline_||!sink_||!failed_.empty())return -1;sink=GST_ELEMENT(gst_object_ref(sink_));}GstSample*s=gst_app_sink_try_pull_sample(GST_APP_SINK(sink),(timeout>0?timeout:1000)*GST_MSECOND);if(!s){std::lock_guard<std::mutex>l(mu_);std::string why=bus_error_locked("NVDEC source lost stream");bool eos=gst_app_sink_is_eos(GST_APP_SINK(sink));gst_object_unref(sink);if(!why.empty()){failed_=why;return -1;}return eos?-1:0;}GstCaps*c=gst_sample_get_caps(s);GstVideoInfo info{};GstBuffer*b=gst_sample_get_buffer(s);std::string why;int w=0,h=0,stride=0;if(!c||!b||!gst_video_info_from_caps(&info,c))why="invalid NVDEC sample";else if(GST_VIDEO_INFO_FORMAT(&info)!=GST_VIDEO_FORMAT_BGRx)why="NVDEC sample is not negotiated BGRx";else{w=GST_VIDEO_INFO_WIDTH(&info);h=GST_VIDEO_INFO_HEIGHT(&info);}if(why.empty()){GstVideoFrame vf;if(!gst_video_frame_map(&vf,&info,b,GST_MAP_READ))why="BGRx sample cannot be mapped";else{stride=GST_VIDEO_FRAME_PLANE_STRIDE(&vf,0);if(w<=0||h<=0||w>8192||h>8192||stride<w*4)why="invalid BGRx stride/geometry";if(why.empty()){auto pix=std::make_shared<std::vector<uint8_t>>(static_cast<size_t>(w)*h*3);auto*src=static_cast<const uint8_t*>(GST_VIDEO_FRAME_PLANE_DATA(&vf,0));for(int y=0;y<h;++y)for(int x=0;x<w;++x){auto*d=pix->data()+(static_cast<size_t>(y)*w+x)*3;auto*q=src+static_cast<size_t>(y)*stride+x*4;d[0]=q[0];d[1]=q[1];d[2]=q[2];}gst_video_frame_unmap(&vf);gst_sample_unref(s);gst_object_unref(sink);o.stream_index=0;o.seq=seq_++;o.wall_ms=wall();o.t_mono_s=mono();o.w=w;o.h=h;o.stride=w*3;o.fmt=PixFmt::BGR888;o.mem=Mem::Host;o.host=pix->data();o.full_w=w;o.full_h=h;o.hold=pix;return 1;}gst_video_frame_unmap(&vf);}}gst_sample_unref(s);gst_object_unref(sink);std::lock_guard<std::mutex>l(mu_);failed_=why.empty()?"NVDEC frame rejected":why;return -1;}
 void close()override{std::lock_guard<std::mutex>l(mu_);close_locked();}const char*decode_path()const override{return "nvdec";}
private:
 void close_locked(){if(pipeline_){gst_element_set_state(pipeline_,GST_STATE_NULL);gst_object_unref(pipeline_);pipeline_=nullptr;}if(sink_){gst_object_unref(sink_);sink_=nullptr;}playing_=false;started_requested_=false;failed_.clear();}
 std::string bus_error_locked(const char*dflt){std::string out;GstBus*b=pipeline_?gst_element_get_bus(pipeline_):nullptr;if(!b)return {};for(GstMessage*m; (m=gst_bus_pop(b));){if(GST_MESSAGE_TYPE(m)==GST_MESSAGE_ERROR){GError*e=nullptr;gchar*dbg=nullptr;gst_message_parse_error(m,&e,&dbg);out=e?e->message:dflt;if(dbg){out+=" (";out+=dbg;out+=")";}if(e)g_error_free(e);g_free(dbg);}else if(GST_MESSAGE_TYPE(m)==GST_MESSAGE_EOS&&!out.size())out="NVDEC source reached EOS";gst_message_unref(m);}gst_object_unref(b);return out;}
 bool build(std::string&e){std::string codec="h264";try{if(spec_.options_json!="{}"&&!spec_.options_json.empty()){auto j=json_parse(spec_.options_json);codec=j.value("codec",codec);}}catch(...){e="invalid stream options";return false;}for(char&c:codec)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));std::string transport=spec_.transport;for(char&c:transport)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));GstRTSPLowerTrans protocols;if(transport.empty()||transport=="tcp")protocols=GST_RTSP_LOWER_TRANS_TCP;else if(transport=="udp")protocols=GST_RTSP_LOWER_TRANS_UDP;else{e="NVDEC source supports transport tcp or udp";return false;}const char*depay=nullptr;const char*parse=nullptr;const char*enc=nullptr;if(codec=="h264"||codec=="avc"){depay="rtph264depay";parse="h264parse";enc="H264";}else if(codec=="h265"||codec=="hevc"){depay="rtph265depay";parse="h265parse";enc="H265";}else{e="NVDEC source supports codec h264 or h265";return false;}GstElement*a=gst_element_factory_make("rtspsrc",nullptr),*d=gst_element_factory_make(depay,nullptr),*p=gst_element_factory_make(parse,nullptr),*n=gst_element_factory_make("nvv4l2decoder",nullptr),*v=gst_element_factory_make("nvvidconv",nullptr),*f=gst_element_factory_make("capsfilter",nullptr),*s=gst_element_factory_make("appsink",nullptr);if(!a||!d||!p||!n||!v||!f||!s){for(GstElement*q:{a,d,p,n,v,f,s})if(q)gst_object_unref(q);e="required NVDEC plugin unavailable (rtspsrc/depay/parser/nvv4l2decoder/nvvidconv/appsink)";return false;}g_object_set(a,"location",spec_.url.c_str(),"protocols",protocols,"latency",100,"drop-on-latency",TRUE,nullptr);GstCaps*caps=gst_caps_new_simple("video/x-raw","format",G_TYPE_STRING,"BGRx",nullptr);g_object_set(f,"caps",caps,nullptr);gst_caps_unref(caps);g_object_set(s,"max-buffers",2u,"drop",TRUE,"sync",FALSE,"emit-signals",FALSE,nullptr);pipeline_=gst_pipeline_new("vb-nvdec-source");if(!pipeline_){for(GstElement*q:{a,d,p,n,v,f,s})gst_object_unref(q);e="failed to allocate NVDEC pipeline";return false;}gst_bin_add_many(GST_BIN(pipeline_),a,d,p,n,v,f,s,nullptr);if(!gst_element_link_many(d,p,n,v,f,s,nullptr)){gst_element_set_state(pipeline_,GST_STATE_NULL);gst_object_unref(pipeline_);pipeline_=nullptr;e="failed to link NVDEC pipeline";return false;}pad_.next=d;pad_.enc=enc;g_signal_connect(a,"pad-added",G_CALLBACK(pad_added),&pad_);sink_=GST_ELEMENT(gst_object_ref(s));return true;}
 StreamSpec spec_;GstElement*pipeline_=nullptr,*sink_=nullptr;PadCtx pad_{};std::mutex mu_;uint64_t seq_=0;bool playing_=false;bool started_requested_=false;std::string failed_;
}; struct Init{Init(){gst_init(nullptr,nullptr);}};
}
std::unique_ptr<FrameSource>make_trt_source(const StreamSpec&s,std::string&e){static Init i;auto p=std::make_unique<NvSource>(s);if(!p->prepare(e))return nullptr;return p;}
}
